//export const BASE_URL  = "http://localhost:8080/api/"
export const BASE_URL  = "http://172.16.6.25:8080/eInvoiceServices/api/"
export const ALFRESCO_BASE_URL  = "http://172.16.6.25:8080/alfresco/api/"
export const LOGIN_API_END_URL = BASE_URL + "login"
export const TOKEN_REFRESH_API_END_URL = BASE_URL+"refresh_token";
export const GET_NAVIGATION_ITEMS = BASE_URL+"navitems";
export const INVITE_PARTNER =  BASE_URL+"partnerInvitation";
export const GET_ALL_INVITATIONS = BASE_URL+"partnerInvitation"
export const GET_REGISTRATION_DETAILS  = BASE_URL+"registrationDetails/"
export const POST_REGISTRATION_DETAILS  =BASE_URL+ "profileActivity/"
export const LOOKUP_FIELDS  = BASE_URL+"lookup"
export const ENQUIRY_API_END_URL=BASE_URL+"enquiry"

export const ENQUIRYGET_API_END_URL=BASE_URL+"enquiries"
export const RECIPIENT_API_END_URL=BASE_URL+"reciepientMapping"
export const GSTIN_MAPPING=BASE_URL+"getGstnList"
// export const RECIPIENT_API_END_URL="http://172.16.6.25:8080/eInvoiceServices/api/RCPT_MAPPNG"
// export const RECIPIENTID_API_END_URL="http://172.16.6.25:8080/eInvoiceServices/api/GET_RCPT_ID"
export const RECIPIENTID_API_END_URL=BASE_URL+"getReciepientId"
export const ALLVENDORS_API_END_URL=BASE_URL+"allVendors"
export const VENDORS_API_END_URL=BASE_URL+"mappedVendors"
export const VENDORSEARCH_API_END_URL=BASE_URL+"allVendors/"
export const NEW_VENDOR_MAPPING=BASE_URL+"newVendorMapping"
export const TODO = BASE_URL+"todo"
export const TODO_STATUS = BASE_URL+"todo/status/"
export const TODO_FLAG = BASE_URL+"todo/flag/"
export const TODO_PRIORITY = BASE_URL+"todo/priority/"

export const API_CHECK =  BASE_URL + "http://localhost:8080/eInvoice_1/v1/web/rest/get_message";
export const ROLE_ACCESS_CHECK = BASE_URL + "private_access";
export const ADD_DOCUMENTS = ALFRESCO_BASE_URL + "addDocuments"
export const DELETE_DOCUMENT = ALFRESCO_BASE_URL + "deleteDocument"
export const GET_DOCUMENT_CONTENT = ALFRESCO_BASE_URL + "getDocumentContent"
export const GET_ALL_INVOICES = BASE_URL + "invoiceList"
export const UPLOAD_INVOICE = BASE_URL + "invoiceUpload"
export const GET_INVOICE_DETAILS = BASE_URL + "getInvoiceDetails"
export const SEARCH_RECIPIENTS = BASE_URL + "myReciepeints"
export const INV_JSON_UPLOAD = BASE_URL+ "inv/json"
